name: Test
on:
  push:
    paths: ['boxman/**','test/**','.flake8','requirements.txt', '.github/workflows/test.yml']
  pull_request:
    paths: ['boxman/**','test/**','.flake8','requirements.txt', '.github/workflows/test.yml']

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint
      run: |
        flake8
    - name: Run tests
      run: |
        python3 -m coverage run -m unittest discover -bv --locals test
    - name: Generate coverage report
      run: |
        echo "**Coverage report**:" >> $GITHUB_STEP_SUMMARY
        echo '```' >> $GITHUB_STEP_SUMMARY
        python -m coverage report >> $GITHUB_STEP_SUMMARY
        echo '```' >> $GITHUB_STEP_SUMMARY
